<?php
/**
 * @var \Favicode\Faq\Block\CustomerQuestions $block
 * @var \Magento\Framework\Escaper $escaper
 */

$questions = $block->getCustomerQuestions();
?>

<hr>
<div>

    <?php if (empty($questions)) : ?>
        <div> <?= $escaper->escapeHtml(__('You haven\'t asked any questions about our products. If you want to ask a question about a product, you can
            do so on product page, after selecting "FAQ" tab')) ?>
        </div>
    <?php else: ?>
        <?php foreach ($questions as $question) : ?>
            <div class="questions-display">
                <div>
                    <div>Q:<strong> <?= $escaper->escapeHtml($question->getQuestionText()) ?> </strong></div>
                    <?php if ($question->getQuestionAnswer() !== null) : ?>
                        <div>A: <?= $escaper->escapeHtml($question->getQuestionAnswer()) ?> </div>
                    <?php else: ?>
                        <div><em><?= $escaper->escapeHtml(__('Sorry, this question is not yet answered')) ?> </em></div>
                    <?php endif; ?>
                </div>

                <div>
                    <div>
                        <a href="<?= $escaper->escapeHtmlAttr($block->getProductLink((int)$question->getProductId(), (int)$question->getStoreId())) ?>">
                            <?= $escaper->escapeHtml(__('Product Link')) ?></a>
                    </div>
                    <div>
                        <a href="<?= $escaper->escapeHtmlAttr($block->getUrl('faq/question/delete', ['question_id' => $question->getId()])) ?>"
                           onclick="return confirm('Are you sure you want to delete this question?')">
                            <?= $escaper->escapeHtml(__('Delete question')) ?>
                        </a>
                    </div>
                </div>

            </div>
            <hr>
        <?php endforeach; ?>
    <?php endif; ?>

</div>
