<?php
/**
 * @var \Favicode\Faq\Block\ProductFaq $block
 * @var \Magento\Framework\Escaper $escaper
 */

$questions = $block->getProductFaq();
$categories = $block->getAllProductCategories();
$numberOfCategories = empty($categories) ? 1 : end($categories)['faq_category_id'];

?>

<h2> FAQ </h2>
<hr>
<div>
    <?php if (empty($questions)) : ?>
        <div class="categories-filter-display">
            <a href="<?= $block->getUrl('*/*/*', ['_use_rewrite' => true]) ?>">
                <button>
                    <?= __('All Questions') ?>
                </button>
            </a>
        </div>
        <p> <?= __('There are no FAQ for this product') ?></p>
    <?php else : ?>
        <div class="categories-filter-display">
            <a href="<?= $block->getUrl('*/*/*', ['_use_rewrite' => true]) ?>">
                <button>
                    <?= __('All Questions') ?>
                </button>
            </a>
            <?php foreach ($categories as $category) : ?>
                <a href="<?= $escaper->escapeHtmlAttr($block->getUrl('*/*/*', ['_use_rewrite' => true]) . '?category_id=' . $category->getCategoryId()) ?>">
                    <button>
                        <?= $escaper->escapeHtml($category->getCategoryName()) ?>
                    </button>
                </a>
            <?php endforeach; ?>
        </div>

        <?php foreach ($questions as $question) : ?>
            <div><strong> <?= $escaper->escapeHtml($question->getQuestionText()) ?> </strong></div>
            <div> <?= $escaper->escapeHtml($question->getQuestionAnswer()) ?> </div>
            <hr>
        <?php endforeach; ?>
    <?php endif; ?>

    <?php if ($block->isLoggedIn()) : ?>
        <div class="columns" style="margin-top: 50px">
            <div>
                <h3> <?= __('Submit your Question') ?></h3>

                <form action="faq/question/save" class="form faq-form" method="post"
                      data-mage-init='{"validation": {}}'>

                    <label for="question_input" class="label faq-label"> <span> <?= __('Question text') ?> </span>
                    </label>
                    <div class="control">
                        <input id="question_input" type="text" name="question_text"
                               class="input-text" data-validate="{'required':true, 'maxlength':255}"
                               aria-required="true">
                    </div>

                    <label for="category_input" class="label faq-label"> <span> <?= __('Category') ?></span> </label>
                    <div class="control">
                        <select id="category_input" name="category_id"
                                data-validate="{'validate-select':true, 'validate-digits-range':'1-<?= $numberOfCategories ?>'}"
                                aria-required="true">
                            <option value="" selected> <?= __('What is this question about...') ?></option>
                            <?php foreach ($categories as $category) : ?>
                                <option
                                    value="<?= $category->getCategoryId() ?>"> <?= $escaper->escapeHtml($category->getCategoryName()) ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>

                    <input type="hidden" name="product_id"
                           value="<?= $escaper->escapeHtmlAttr($block->getProductId()) ?>">
                    <input type="submit" class="action submit primary" value="Submit">
                </form>
            </div>
        </div>
    <?php else: ?>
        <h3> <?= __('To ask question, please log in first') ?></h3>
    <?php endif; ?>

</div>
